import type { IUser } from "@/types/iims.types";

export const SEED_USERS: IUser[] = [
  {
    id: "1",
    email: "se@iims.gov.in",
    password: "se123",
    role: "Sectional Engineer",
    name: "Rajesh Kumar",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:30 AM",
  },
  {
    id: "2",
    email: "de@iims.gov.in",
    password: "de123",
    role: "Deputy Engineer",
    name: "Priya Sharma",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-02 02:15 PM",
  },
  {
    id: "3",
    email: "ee@iims.gov.in",
    password: "ee123",
    role: "Executive Engineer",
    name: "Amit Deshmukh",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-02-25 04:30 PM",
  },
  {
    id: "4",
    email: "clerk@iims.gov.in",
    password: "clerk123",
    role: "Tender Clerk",
    name: "Sunita Patil",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
  {
    id: "5",
    email: "auditor@iims.gov.in",
    password: "auditor123",
    role: "Auditor",
    name: "Vijay Jadhav",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-07 04:15 PM",
  },
  {
    id: "6",
    email: "accountant@iims.gov.in",
    password: "accountant123",
    role: "Accountant",
    name: "Kavita Reddy",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 02:00 PM",
  },
  {
    id: "7",
    email: "aao@iims.gov.in",
    password: "aao123",
    role: "Assistant Accounts Officer",
    name: "Suresh Pawar",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-05 11:00 AM",
  },
  {
    id: "8",
    email: "cafo@iims.gov.in",
    password: "cafo123",
    role: "Chief Accounts and Finance Officer",
    name: "Ramesh Kulkarni",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-07 11:30 AM",
  },
  {
    id: "9",
    email: "addl-ceo@iims.gov.in",
    password: "addlceo123",
    role: "Additional Chief Executive Officer",
    name: "Ashok Mehta",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-05 10:30 AM",
  },
  {
    id: "10",
    email: "ceo@iims.gov.in",
    password: "ceo123",
    role: "Chief Executive Officer",
    name: "Anjali Verma",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 02:00 PM",
  },
  {
    id: "11",
    email: "admin@iims.gov.in",
    password: "admin123",
    role: "System Administrator",
    name: "Santosh Naik",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
  {
    id: "12",
    email: "contractor@iims.gov.in",
    password: "contractor123",
    role: "Contractor",
    name: "Mahesh Builders Pvt Ltd",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
  {
    id: "13",
    email: "configurator@iims.gov.in",
    password: "config123",
    role: "Technical System Configurator",
    name: "Vijay Patwardhan",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
];
