import type { IUser } from "@/types/iims.types";

export const SEED_USERS: IUser[] = [
  {
    id: "USR-2026-0001",
    email: "se@iims.gov.in",
    password: "se123",
    role: "Sectional Engineer",
    name: "Rajesh Kumar",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:30 AM",
  },
  {
    id: "USR-2026-0002",
    email: "de@iims.gov.in",
    password: "de123",
    role: "Deputy Engineer",
    name: "Priya Sharma",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-02 02:15 PM",
  },
  {
    id: "USR-2026-0003",
    email: "ee@iims.gov.in",
    password: "ee123",
    role: "Executive Engineer",
    name: "Amit Deshmukh",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-02-25 04:30 PM",
  },
  {
    id: "USR-2026-0004",
    email: "clerk@iims.gov.in",
    password: "clerk123",
    role: "Tender Clerk",
    name: "Sunita Patil",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
  {
    id: "USR-2026-0005",
    email: "auditor@iims.gov.in",
    password: "auditor123",
    role: "Auditor",
    name: "Vijay Jadhav",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-07 04:15 PM",
  },
  {
    id: "USR-2026-0006",
    email: "accountant@iims.gov.in",
    password: "accountant123",
    role: "Accountant",
    name: "Kavita Reddy",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 02:00 PM",
  },
  {
    id: "USR-2026-0007",
    email: "aao@iims.gov.in",
    password: "aao123",
    role: "Assistant Accounts Officer",
    name: "Suresh Pawar",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-05 11:00 AM",
  },
  {
    id: "USR-2026-0008",
    email: "cafo@iims.gov.in",
    password: "cafo123",
    role: "Chief Accounts and Finance Officer",
    name: "Ramesh Kulkarni",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-07 11:30 AM",
  },
  {
    id: "USR-2026-0009",
    email: "addl-ceo@iims.gov.in",
    password: "addlceo123",
    role: "Additional Chief Executive Officer",
    name: "Ashok Mehta",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-05 10:30 AM",
  },
  {
    id: "USR-2026-0010",
    email: "ceo@iims.gov.in",
    password: "ceo123",
    role: "Chief Executive Officer",
    name: "Anjali Verma",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 02:00 PM",
  },
  {
    id: "USR-2026-0011",
    email: "admin@iims.gov.in",
    password: "admin123",
    role: "System Administrator",
    name: "Santosh Naik",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
  {
    id: "USR-2026-0012",
    email: "mahesh.builders@iims.gov.in",
    password: "contractor123",
    role: "Contractor",
    userType: "Contractor",
    name: "Mahesh Tiwari",
    firstName: "Mahesh",
    middleName: "",
    lastName: "Tiwari",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    mobile: "9876501234",
    panNo: "AABCT1234D",
    firm: "Mahesh Builders Pvt Ltd",
    firmAddress: "Plot 45, Bhosari MIDC, Pune - 411026",
    address: "Flat 3B, Shivneri Apartments, Wakad, Pune - 411057",
    designations: ["Contractor"],
    departments: ["Public Works"],
    divisions: ["Pune Division"],
    subDivisions: ["Khed Sub Division"],
    lastLogin: "2026-03-01 10:00 AM",
  },
  {
    id: "USR-2026-0013",
    email: "configurator@iims.gov.in",
    password: "config123",
    role: "Technical System Configurator",
    name: "Vijay Patwardhan",
    status: "Active",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    lastLogin: "2026-03-01 10:00 AM",
  },
  // ── Contractor accounts (linked to SEED_CONTRACTORS via email / userId) ──────
  {
    id: "USR-2026-0014",
    email: "amit.patil@abcinfra.in",
    password: "contractor123",
    role: "Contractor",
    userType: "Contractor",
    name: "Amit Patil",
    firstName: "Amit",
    middleName: "",
    lastName: "Patil",
    status: "Active",
    mobile: "9876543210",
    panNo: "ABCPA1234A",
    firm: "ABC Infra Pvt Ltd",
    firmAddress: "Plot 12, MIDC, Hadapsar, Pune - 411028",
    address: "Flat 304, Sai Residency, Hadapsar, Pune - 411028",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    designations: ["Contractor"],
    departments: ["Public Works"],
    divisions: ["Pune Division"],
    subDivisions: ["Khed Sub Division"],
    lastLogin: "2026-03-10 09:30 AM",
  },
  {
    id: "USR-2026-0015",
    email: "ramesh.jadhav@saiconstruction.in",
    password: "contractor123",
    role: "Contractor",
    userType: "Contractor",
    name: "Ramesh Kulkarni",
    firstName: "Ramesh",
    middleName: "",
    lastName: "Kulkarni",
    status: "Active",
    mobile: "9765432109",
    panNo: "ADFPJ5678B",
    firm: "Sai Construction",
    firmAddress: "Survey No. 45, Wagholi, Pune - 412207",
    address: "Plot 23, Indrayani Nagar, Wagholi, Pune - 412207",
    division: "Pune Division",
    subDivision: "Maval Sub Division",
    designations: ["Contractor"],
    departments: ["Public Works"],
    divisions: ["Pune Division"],
    subDivisions: ["Maval Sub Division"],
    lastLogin: "2026-03-08 11:00 AM",
  },
  {
    id: "USR-2026-0016",
    email: "suresh.kulkarni@sgbuilders.in",
    password: "contractor123",
    role: "Contractor",
    userType: "Contractor",
    name: "Sunil Deshmukh",
    firstName: "Sunil",
    middleName: "",
    lastName: "Deshmukh",
    status: "Active",
    mobile: "9654321098",
    panNo: "BCDPK9012C",
    firm: "Shree Ganesh Builders",
    firmAddress: "Gat No. 78, Near Khed Bus Stand, Khed, Pune - 410501",
    address: "Gat No. 78, Khed, Pune - 410501",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    designations: ["Contractor"],
    departments: ["Public Works"],
    divisions: ["Pune Division"],
    subDivisions: ["Khed Sub Division"],
    lastLogin: "2026-02-28 03:45 PM",
  },
  {
    id: "USR-2026-0017",
    email: "vijay.patil@pew.co.in",
    password: "contractor123",
    role: "Contractor",
    userType: "Contractor",
    name: "Prakash Patil",
    firstName: "Prakash",
    middleName: "",
    lastName: "Patil",
    status: "Active",
    mobile: "9543210987",
    panNo: "CDEPV3456D",
    firm: "Patil Engineering Works",
    firmAddress: "Gut No. 120, Main Road, Shirur, Pune - 412210",
    address: "Gut No. 120, Shirur, Pune - 412210",
    division: "Pune Division",
    subDivision: "Thane Sub Division",
    designations: ["Contractor"],
    departments: ["Public Works"],
    divisions: ["Pune Division"],
    subDivisions: ["Thane Sub Division"],
    lastLogin: "2026-03-05 02:00 PM",
  },
  {
    id: "USR-2026-0018",
    email: "mahesh.sawant@mahadevinf.in",
    password: "contractor123",
    role: "Contractor",
    userType: "Contractor",
    name: "Mahesh Jadhav",
    firstName: "Mahesh",
    middleName: "",
    lastName: "Jadhav",
    status: "Active",
    mobile: "9432109876",
    panNo: "DEFPM7890E",
    firm: "Mahadev Infrastructure",
    firmAddress: "Gut No. 55, Baramati Road, Baramati, Pune - 413102",
    address: "Gut No. 55, Baramati, Pune - 413102",
    division: "Pune Division",
    subDivision: "Maval Sub Division",
    designations: ["Contractor"],
    departments: ["Public Works"],
    divisions: ["Pune Division"],
    subDivisions: ["Maval Sub Division"],
    lastLogin: "2026-03-12 10:15 AM",
  },
];
