"use client";

import { useState, useRef, useEffect } from "react";
import {
  Sparkles,
  CheckCircle2,
  Upload,
  Download,
  FileText,
  X,
  Loader2,
  AlertCircle,
} from "lucide-react";
import { toast } from "sonner";
import type { WizardState } from "./wizard-types";
import { DEMO_FILL } from "./wizard-types";

// ── Types ─────────────────────────────────────────────────────────────────────

type UploadPhase = "idle" | "parsing" | "success" | "error";

interface ParseStage {
  label: string;
  durationMs: number;
}

const PARSE_STAGES: ParseStage[] = [
  { label: "Reading file content...", durationMs: 350 },
  { label: "Identifying project structure...", durationMs: 400 },
  { label: "Extracting field values...", durationMs: 350 },
  { label: "Populating form fields...", durationMs: 250 },
];

// Fields shown in the success summary (label → what value was filled)
const DETECTED_FIELDS = [
  { label: "Work Name", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).projectName },
  { label: "Sanction Year", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).sanctionYear },
  { label: "Department", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).departmentName },
  { label: "Major Head", value: `${(DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).majorHeadName} (${(DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).majorHeadCode})` },
  { label: "Division", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).division },
  { label: "Sub Division", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).subDivision },
  { label: "Taluka / Gram Panchayat", value: `${(DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).taluka} / ${(DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).gramPanchayat}` },
  { label: "SSR Reference", value: `${(DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).ssrType} · ${(DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).ssrYear}` },
  { label: "Work Activity", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).workActivity },
  { label: "Work Demand By", value: (DEMO_FILL.basicDetails as NonNullable<typeof DEMO_FILL.basicDetails>).workDemandBy },
  { label: `Sub-Works detected`, value: `${DEMO_FILL.subWorks?.length ?? 0} items` },
  { label: "Lead Statements detected", value: `${DEMO_FILL.leadStatements?.length ?? 0} items` },
  { label: "Rate Analysis items", value: `${DEMO_FILL.rateAnalysis?.length ?? 0} items` },
  { label: "Measurements", value: `${DEMO_FILL.measurements?.length ?? 0} entries` },
];

// ── Sample file content ───────────────────────────────────────────────────────

const SAMPLE_FILE_CONTENT = `IIMS PROJECT SPECIFICATION FILE
================================
Generated by: Integrated Infrastructure Management System
Template Version: 2024-1.0

PROJECT DETAILS
---------------
Work Name: Hadapsar Metro Station Approach Road Construction
Sanction Year: 2024-2025
Department: Works
Major Head: Transport Infrastructure
Major Head Code: 4202
Division: Pune Division
Sub Division: Khed Sub Division
Taluka: Khed
Gram Panchayat: Hadapsar Gram Panchayat
SSR Type: SSR-PWD
SSR Year: 2024-2025
DSR Type: DSR-001
Work Activity: Road Works
Work Demand By: Zilla Parishad

SUB-WORKS
---------
1. Approach Road Construction - Phase 1
2. Drainage System Installation
3. Street Lighting

LEAD STATEMENTS
---------------
Material: Sand | Source: Local Quarry | Distance: 15 km | Rate: ₹150/km
Material: Cement | Source: ACC Depot Pune | Distance: 25 km | Rate: ₹150/km
Material: Aggregate | Source: Crusher Plant Khed | Distance: 20 km | Rate: ₹150/km

RATE ANALYSIS
-------------
Item 1.1: Road Base Course - WBM Grading III
  Material: ₹45,000 | Labour: ₹15,000 | Machinery: ₹8,000 | Base: ₹5,000
  Total Rate: ₹73,000

Item 1.2: Bituminous Macadam (BM) - 75mm
  Material: ₹62,000 | Labour: ₹18,000 | Machinery: ₹12,000 | Base: ₹8,000
  Total Rate: ₹1,00,000

MEASUREMENT SHEET
-----------------
Item 1.1: WBM Base Course
  L: 500m × B: 7m × H: 0.2m | Qty: 700 Cum | Rate: ₹4,500 | Amount: ₹31,50,000

Item 1.2: Bituminous Macadam Layer
  L: 500m × B: 7m × H: 0.075m | Qty: 262.5 Cum | Rate: ₹8,500 | Amount: ₹22,31,250

GENERAL DESCRIPTION
-------------------
Technical Notes:
Construction of approach road to Hadapsar Metro Station as per IRC standards.
The road shall be designed for mixed traffic including heavy vehicles.
All materials shall conform to MORTH specifications.

Site Conditions:
Site is located in urban area with existing utilities.
Coordination with MSEDCL and PUNE Mahanagar Palika required for shifting of utilities.
Soil bearing capacity as per soil investigation report.

Special Clauses:
Contractor shall maintain traffic diversion during construction.
Night work may be required in certain stretches.
Quality control tests as per QAP to be maintained.

--- END OF FILE ---
`;

function downloadSampleFile() {
  const blob = new Blob([SAMPLE_FILE_CONTENT], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "IIMS_Sample_Project_Specification.txt";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  toast.success("Sample file downloaded", {
    description: "Upload it back to see AI auto-fill in action.",
  });
}

// ── Props ─────────────────────────────────────────────────────────────────────

interface Props {
  uploadedFileName: string;
  isAutoFilled: boolean;
  onFill: (patch: Partial<WizardState>) => void;
  onReset: () => void;
}

// ── Component ─────────────────────────────────────────────────────────────────

export function AIUploadPanel({ uploadedFileName, isAutoFilled, onFill, onReset }: Props) {
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Derive phase from props so it's always in sync when draft is loaded
  const derivedPhase: UploadPhase = isAutoFilled ? "success" : "idle";
  const [phase, setPhase] = useState<UploadPhase>(derivedPhase);
  const [stageIdx, setStageIdx] = useState(0);
  const [fileName, setFileName] = useState(uploadedFileName);

  // Keep local state in sync when parent resets
  useEffect(() => {
    if (!isAutoFilled && !uploadedFileName) {
      setPhase("idle");
      setFileName("");
      setStageIdx(0);
    } else if (isAutoFilled && uploadedFileName) {
      setPhase("success");
      setFileName(uploadedFileName);
    }
  }, [isAutoFilled, uploadedFileName]);

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;

    const allowed = [".txt", ".doc", ".docx", ".pdf"];
    const ext = file.name.slice(file.name.lastIndexOf(".")).toLowerCase();
    if (!allowed.includes(ext)) {
      toast.error("Unsupported file type", { description: "Please upload a .txt, .doc, .docx or .pdf file." });
      return;
    }

    setFileName(file.name);
    setPhase("parsing");
    setStageIdx(0);
    runParseStages(file);
  }

  function runParseStages(file: File) {
    let elapsed = 0;
    PARSE_STAGES.forEach((stage, idx) => {
      elapsed += stage.durationMs;
      setTimeout(() => setStageIdx(idx), elapsed - stage.durationMs);
    });

    const totalMs = PARSE_STAGES.reduce((s, st) => s + st.durationMs, 0);
    setTimeout(() => {
      setPhase("success");
      onFill({
        ...(DEMO_FILL as Partial<WizardState>),
        uploadedFileName: file.name,
        isDataAutoFilled: true,
      });
    }, totalMs);
  }

  function handleReset() {
    setPhase("idle");
    setFileName("");
    setStageIdx(0);
    onReset();
  }

  function handleDrop(e: React.DragEvent<HTMLDivElement>) {
    e.preventDefault();
    const file = e.dataTransfer.files?.[0];
    if (file) {
      const synth = { target: { files: e.dataTransfer.files, value: "" } } as unknown as React.ChangeEvent<HTMLInputElement>;
      handleFileChange(synth);
    }
  }

  return (
    <div className="bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 border-2 border-dashed border-purple-300 dark:border-purple-600 rounded-xl p-6">
      <input
        ref={fileInputRef}
        type="file"
        accept=".txt,.doc,.docx,.pdf"
        className="hidden"
        onChange={handleFileChange}
      />

      {/* Header row */}
      <div className="flex items-start gap-4">
        <div
          className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 transition-colors ${
            phase === "success"
              ? "bg-green-100 dark:bg-green-900/40"
              : "bg-purple-100 dark:bg-purple-900/40"
          }`}
        >
          {phase === "parsing" ? (
            <Loader2 className="w-5 h-5 text-purple-600 dark:text-purple-400 animate-spin" />
          ) : phase === "success" ? (
            <CheckCircle2 className="w-5 h-5 text-green-600 dark:text-green-400" />
          ) : (
            <Sparkles className="w-5 h-5 text-purple-600 dark:text-purple-400" />
          )}
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1">
            <span className="font-semibold text-gray-900 dark:text-gray-100">
              AI-Assisted Project Upload
            </span>
            {phase === "success" && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-300 text-xs font-medium">
                <CheckCircle2 className="w-3 h-3" /> Auto-filled
              </span>
            )}
          </div>

          <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">
            Upload a project specification file and let AI extract all details automatically.{" "}
            <button
              type="button"
              onClick={downloadSampleFile}
              className="inline-flex items-center gap-1 text-purple-600 dark:text-purple-400 hover:text-purple-800 dark:hover:text-purple-200 font-medium transition-colors"
            >
              <Download className="w-3 h-3" />
              Download sample file
            </button>
          </p>

          {/* ── IDLE state ── */}
          {phase === "idle" && (
            <div
              className="flex flex-col sm:flex-row items-center gap-3"
              onDragOver={(e) => e.preventDefault()}
              onDrop={handleDrop}
            >
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium transition-colors shadow-sm"
              >
                <Upload className="w-4 h-4" />
                Upload Project File
              </button>
              <span className="text-xs text-gray-400 dark:text-gray-500">
                .txt, .doc, .docx, .pdf · drag & drop supported
              </span>
            </div>
          )}

          {/* ── PARSING state ── */}
          {phase === "parsing" && (
            <div className="space-y-3">
              {/* File being processed */}
              <div className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-gray-800 border border-purple-200 dark:border-purple-700 rounded-lg text-sm">
                <FileText className="w-4 h-4 text-purple-500 flex-shrink-0" />
                <span className="text-gray-700 dark:text-gray-300 truncate flex-1">{fileName}</span>
              </div>

              {/* Stage progress */}
              <div className="space-y-1.5">
                {PARSE_STAGES.map((stage, idx) => {
                  const done = idx < stageIdx;
                  const active = idx === stageIdx;
                  return (
                    <div key={idx} className="flex items-center gap-2">
                      <div
                        className={`w-4 h-4 rounded-full flex items-center justify-center flex-shrink-0 transition-all ${
                          done
                            ? "bg-green-500"
                            : active
                            ? "bg-purple-500"
                            : "bg-gray-200 dark:bg-gray-700"
                        }`}
                      >
                        {done ? (
                          <CheckCircle2 className="w-3 h-3 text-white" />
                        ) : active ? (
                          <div className="w-1.5 h-1.5 rounded-full bg-white animate-pulse" />
                        ) : null}
                      </div>
                      <span
                        className={`text-xs transition-colors ${
                          done
                            ? "text-green-600 dark:text-green-400 line-through"
                            : active
                            ? "text-purple-700 dark:text-purple-300 font-medium"
                            : "text-gray-400 dark:text-gray-500"
                        }`}
                      >
                        {stage.label}
                      </span>
                    </div>
                  );
                })}
              </div>

              {/* Animated progress bar */}
              <div className="w-full h-1.5 bg-purple-100 dark:bg-purple-900/30 rounded-full overflow-hidden">
                <div
                  className="h-full bg-purple-500 rounded-full transition-all duration-300"
                  style={{ width: `${((stageIdx + 1) / PARSE_STAGES.length) * 100}%` }}
                />
              </div>
            </div>
          )}

          {/* ── SUCCESS state ── */}
          {phase === "success" && (
            <div className="space-y-3">
              {/* File row */}
              <div className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-gray-800 border border-green-200 dark:border-green-700 rounded-lg text-sm">
                <FileText className="w-4 h-4 text-green-500 flex-shrink-0" />
                <span className="text-gray-700 dark:text-gray-300 truncate flex-1">{fileName}</span>
                <button
                  type="button"
                  onClick={handleReset}
                  className="p-1 rounded bg-red-50 dark:bg-red-900/20 text-red-500 hover:bg-red-100 dark:hover:bg-red-900/40 transition-colors flex-shrink-0"
                  title="Reset"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Success banner */}
              <div className="flex items-center gap-2 px-3 py-2 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-700 rounded-lg">
                <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0" />
                <p className="text-sm text-green-700 dark:text-green-300 font-medium">
                  Data auto-filled successfully! Please review all fields below.
                </p>
              </div>

              {/* Detected fields grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
                {DETECTED_FIELDS.map((field) => (
                  <div
                    key={field.label}
                    className="flex items-start gap-2 px-2 py-1.5 bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-md"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5 text-green-500 flex-shrink-0 mt-0.5" />
                    <div className="min-w-0">
                      <p className="text-xs text-gray-500 dark:text-gray-400">{field.label}</p>
                      <p className="text-xs font-medium text-gray-700 dark:text-gray-300 truncate">{field.value}</p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Reset link */}
              <p className="text-xs text-gray-400 dark:text-gray-500">
                Not what you expected?{" "}
                <button
                  type="button"
                  onClick={handleReset}
                  className="text-red-500 hover:text-red-700 dark:hover:text-red-300 underline font-medium"
                >
                  Reset and upload a different file
                </button>
              </p>
            </div>
          )}

          {/* ── ERROR state (defensive) ── */}
          {phase === "error" && (
            <div className="flex items-center gap-2 px-3 py-2 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 rounded-lg text-sm">
              <AlertCircle className="w-4 h-4 text-red-500 flex-shrink-0" />
              <span className="text-red-700 dark:text-red-300">
                Failed to parse file.{" "}
                <button type="button" onClick={handleReset} className="underline">
                  Try again
                </button>
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
