export interface BasicDetails {
  projectName: string;
  sanctionYear: string;
  departmentName: string;
  majorHeadName: string;
  majorHeadCode: string;
  division: string;
  subDivision: string;
  taluka: string;
  gramPanchayat: string;
  ssrType: string;
  ssrYear: string;
  dsrType: string;
  workActivity: string;
  workDemandBy: string;
  workDemandByDocumentName: string;
  workDemandByDocumentFile?: UploadedFile;
}

export interface UploadedFile {
  id: string;
  name: string;
  type: string;
  url: string;
  size?: number;
}

export interface SubWorkItem {
  id: string;
  name: string;
}

export interface LeadStatementItem {
  id: string;
  materialName: string;
  sourceOfSupply: string;
  kilometer: number;
  calculation: number;
}

// A charge the user has chosen to apply, with an optionally overridden percentage.
// Separate from ICharge so the percentage can differ from the configured default.
export interface AppliedCharge {
  chargeId:   string;
  type:       string;
  percentage: number;
}

export interface RateItem {
  id: string;
  itemNumber: string;
  itemDescription: string;
  materialComponents: number;
  laborComponents: number;
  machineryComponents: number;
  baseRate: number;
  totalRate: number;
  remarks: string;
}

export interface MeasurementItem {
  id: string;
  itemNumber: string;
  itemName: string;
  length: number;
  breadth: number;
  height: number;
  quantity: number;
  unit: string;
  rate: number;
  amount: number;
}

export interface GeneralDescription {
  technicalNotes: string;
  siteConditions: string;
  specialClauses: string;
}

// Categorised upload buckets for Step 7
export interface UploadedDocumentSet {
  drawings:      UploadedFile[];
  sitePhotos:    UploadedFile[];
  surveyReports: UploadedFile[];
}

export const BLANK_DOCUMENT_SET: UploadedDocumentSet = {
  drawings:      [],
  sitePhotos:    [],
  surveyReports: [],
};

// Valid item numbers from the SSR master list (must stay in sync with SSR_ITEMS in step4-rate-analysis.tsx)
export const VALID_SSR_ITEM_NUMBERS = ["24.01", "21.40", "2.10"] as const;

// Documents auto-generated by the system on submission (informational only)
export const AUTO_GENERATED_DOCS = [
  { id: "abstract-sheet",        name: "Abstract Sheet"             },
  { id: "quality-control-sheet", name: "Quality Control Sheet"      },
  { id: "royalty-sheet",         name: "Royalty Sheet"              },
  { id: "material-consumption",  name: "Material Consumption Sheet" },
] as const;

export interface WizardState {
  basicDetails: BasicDetails;
  subWorks: SubWorkItem[];
  leadStatements: LeadStatementItem[];
  rateAnalysis: RateItem[];
  measurements: MeasurementItem[];
  generalDescription: GeneralDescription;
  documents: UploadedFile[];
  documentSets: UploadedDocumentSet;
  verificationChecked: boolean;
  draftId?: string;
  uploadedFileName?: string;
  isDataAutoFilled: boolean;
}

export const STEP_NAMES = [
  "Create Project",
  "Item Sub Work",
  "Lead Statement",
  "Rate Analysis",
  "Measurement Sheet",
  "General Description",
  "Upload Documents",
  "Review & Submit",
] as const;

export const MAJOR_HEAD_CODES: Record<string, string> = {
  "Social Infrastructure": "4059",
  "Transport Infrastructure": "4202",
  "Water Supply and Sanitation": "4215",
  "Public Buildings": "4059",
};

export const BLANK_BASIC: BasicDetails = {
  projectName: "",
  sanctionYear: "",
  departmentName: "",
  majorHeadName: "",
  majorHeadCode: "",
  division: "",
  subDivision: "",
  taluka: "",
  gramPanchayat: "",
  ssrType: "",
  ssrYear: "",
  dsrType: "",
  workActivity: "",
  workDemandBy: "",
  workDemandByDocumentName: "",
  workDemandByDocumentFile: undefined,
};

export const DEMO_FILL: Partial<WizardState> = {
  basicDetails: {
    projectName: "Hadapsar Metro Station Approach Road Construction",
    sanctionYear: "2024-2025",
    departmentName: "Works",
    majorHeadName: "Transport Infrastructure",
    majorHeadCode: "4202",
    division: "Pune Division",
    subDivision: "Khed Sub Division",
    taluka: "Khed",
    gramPanchayat: "Hadapsar Gram Panchayat",
    ssrType: "SSR-PWD",
    ssrYear: "2024-2025",
    dsrType: "DSR-001",
    workActivity: "Road Works",
    workDemandBy: "Zilla Parishad",
    workDemandByDocumentName: "",
  },
  subWorks: [
    { id: "sw-1", name: "Approach Road Construction - Phase 1" },
    { id: "sw-2", name: "Drainage System Installation" },
    { id: "sw-3", name: "Street Lighting" },
  ],
  leadStatements: [
    { id: "ls-1", materialName: "Sand", sourceOfSupply: "Local Quarry", kilometer: 15, calculation: 2250 },
    { id: "ls-2", materialName: "Cement", sourceOfSupply: "ACC Depot Pune", kilometer: 25, calculation: 3750 },
    { id: "ls-3", materialName: "Aggregate", sourceOfSupply: "Crusher Plant Khed", kilometer: 20, calculation: 3000 },
  ],
  rateAnalysis: [
    {
      id: "ra-1",
      itemNumber: "24.01",
      itemDescription: "Providing and laying Cast in situ/Ready Mix cement concrete in M-10 of trap/granite/quartzite/gneiss metal for foundation and bedding including bailing out water, steel centering, formwork, laying/pumping, compacting, roughening if special finish is required, finishing if required and curing complete, with fully automatic microprocessor based PLC with SCADA enabled reversible Drum Type mixer/concrete Batch mix plant (Pan mixer) etc. complete. With fine aggregate (Natural Sand / Crushed Sand VSI Grade finely washed etc.) : PWD-2022-2023",
      materialComponents: 45000,
      laborComponents: 15000,
      machineryComponents: 8000,
      baseRate: 5000,
      totalRate: 73000,
      remarks: "As per SSR-PWD 2024-25",
    },
    {
      id: "ra-2",
      itemNumber: "21.40",
      itemDescription: "Providing soling using 80 mm size trap metal in 15 cm layer including filling voids with crushed sand/grit, ramming, watering etc. complete.",
      materialComponents: 62000,
      laborComponents: 18000,
      machineryComponents: 12000,
      baseRate: 8000,
      totalRate: 100000,
      remarks: "",
    },
  ],
  measurements: [
    {
      id: "ms-1",
      itemNumber: "1.1",
      itemName: "WBM Base Course",
      length: 500,
      breadth: 7,
      height: 0.2,
      quantity: 700,
      unit: "Cum",
      rate: 4500,
      amount: 3150000,
    },
    {
      id: "ms-2",
      itemNumber: "1.2",
      itemName: "Bituminous Macadam Layer",
      length: 500,
      breadth: 7,
      height: 0.075,
      quantity: 262.5,
      unit: "Cum",
      rate: 8500,
      amount: 2231250,
    },
  ],
  generalDescription: {
    technicalNotes:
      "Construction of approach road to Hadapsar Metro Station as per IRC standards. The road shall be designed for mixed traffic including heavy vehicles. All materials shall conform to MORTH specifications.",
    siteConditions:
      "Site is located in urban area with existing utilities. Coordination with MSEDCL and PUNE Mahanagar Palika required for shifting of utilities. Soil bearing capacity as per soil investigation report.",
    specialClauses:
      "Contractor shall maintain traffic diversion during construction. Night work may be required in certain stretches. Quality control tests as per QAP to be maintained.",
  },
};
